sudo: required
language: node_js
services:
  - docker
  - mongodb
  - postgresql
node_js:
  - 10
  - 12
  - 14
install:
  - npm install
before_script:
  - sudo service mysql stop
  - docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=yourStrong(!)Password' -p 14330:1433 -d mcr.microsoft.com/mssql/server:2017-CU8-ubuntu
script:
  - gulp init
  - gulp lint
  - gulp test
env:
  global:
  - PGPORT=14200
  - PGPASSWORD=test


