name: Integration Tests CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # node-version: [10.x, 12.x, 14.x]
        node-version: [10.x]
        mongodb-version: ['4.4']
    env:
      DB_DATABASE: test_db
      DB_USER: root
      DB_PASSWORD: root

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.7.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
    - name: Setup PostgreSQL on Ubuntu
      run: |
          sudo systemctl start postgresql.service
          pg_isready
    - name: Create PostgreSQL testuser user
      run: |
        sudo -u postgres psql --command="CREATE USER testuser PASSWORD 'testpassword'" --command="\du"
    - name: Set up MySQL
      run: |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
    - name: Start SQL Server
      run: |
        docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=yourStrong(!)Password' -p 14330:1433 -d mcr.microsoft.com/mssql/server:2017-CU8-ubuntu
    - run: npm install
    - run: gulp test

